services:
  backend:
    build: ./backend
    ports: 
      - 8003:8000
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - 8001:8000
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    container_name: frontend
  database:
    image: mariadb:11.7.2-ubi9
    container_name: database
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: movies_db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3