version: '3.8'

services:
  backend:
    build: ./backend
    ports: 
      - 8003:8000
    container_name: backend
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 8001:8000
    #environment:
    #  BACKEND_URL: http://backend:8003
    depends_on:
      - backend
    container_name: frontend
  database:
    image: mariadb:11.7.2-ubi9
    container_name: database
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: movies_db